services:
  - type: web
    name: dino-festas-api
    env: docker
    repo: https://gitlab.com/SEU-USUARIO/dino-festas.git
    branch: main
    dockerfilePath: backend/api/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
